// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pveyylhlerppiwcywcyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2ZXl5bGhsZXJwcGl3Y3l3Y3liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyMzUxNTAsImV4cCI6MjA1MzgxMTE1MH0.hy27xk-DKKUqLmWxx3TkaaniohCAbwhkVp4jV0N8Q7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);